<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>jp.co.ogis-ri.nautible.app</groupId>
  <artifactId>nautible-app-ms-customer-parent</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <org.mapstruct.version>1.6.3</org.mapstruct.version>
    <swagger-annotations.version>1.6.15</swagger-annotations.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>3.21.4</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>3.21.4</quarkus.platform.version>
    <surefire-plugin.version>3.5.3</surefire-plugin.version>
    <validation-api.version>2.0.1.Final</validation-api.version>
    <javax.annotation-api.version>1.3.2</javax.annotation-api.version>
    <javax.interceptor-api.version>1.2.2</javax.interceptor-api.version>
    <javax.ws.rs-api.version>2.1.1</javax.ws.rs-api.version>
    <cdi-api.version>2.0.SP1</cdi-api.version>
    <maven.compiler.release>21</maven.compiler.release>
    <openapi.generator.maven.plugin.version>7.13.0</openapi.generator.maven.plugin.version>
    <nautible.app.customer.groupId>jp.co.ogis-ri.nautible.app</nautible.app.customer.groupId>
    <nautible.app.customer.name>nautible-app-ms-customer</nautible.app.customer.name>
    <nautible.app.customer.version>1.0.0-SNAPSHOT</nautible.app.customer.version>
    <jandex.maven.plugin.version>1.2.3</jandex.maven.plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- struct -->
      <dependency>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct</artifactId>
        <version>${org.mapstruct.version}</version>
      </dependency>
      <dependency>
        <groupId>org.mapstruct</groupId>
        <artifactId>mapstruct-processor</artifactId>
        <version>${org.mapstruct.version}</version>
        <scope>provided</scope>
      </dependency>
      <!-- https://mvnrepository.com/artifact/io.swagger/swagger-annotations -->
      <dependency>
        <groupId>io.swagger</groupId>
        <artifactId>swagger-annotations</artifactId>
        <version>${swagger-annotations.version}</version>
      </dependency>
      <dependency>
        <groupId>javax.validation</groupId>
        <artifactId>validation-api</artifactId>
        <version>${validation-api.version}</version>
      </dependency>
      <dependency>
        <groupId>javax.annotation</groupId>
        <artifactId>javax.annotation-api</artifactId>
        <version>${javax.annotation-api.version}</version>
      </dependency>
      <dependency>
        <groupId>javax.interceptor</groupId>
        <artifactId>javax.interceptor-api</artifactId>
        <version>${javax.interceptor-api.version}</version>
      </dependency>
      <dependency>
        <groupId>javax.ws.rs</groupId>
        <artifactId>javax.ws.rs-api</artifactId>
        <version>${javax.ws.rs-api.version}</version>
      </dependency>
      <dependency>
        <groupId>javax.enterprise</groupId>
        <artifactId>cdi-api</artifactId>
        <version>${cdi-api.version}</version>
      </dependency>
      <dependency>
        <groupId>${nautible.app.customer.groupId}</groupId>
        <artifactId>${nautible.app.customer.name}-core</artifactId>
        <version>${nautible.app.customer.version}</version>
      </dependency>
      <dependency>
        <groupId>${nautible.app.customer.groupId}</groupId>
        <artifactId>${nautible.app.customer.name}-aws</artifactId>
        <version>${nautible.app.customer.version}</version>
      </dependency>
      <dependency>
        <groupId>${nautible.app.customer.groupId}</groupId>
        <artifactId>${nautible.app.customer.name}-azure</artifactId>
        <version>${nautible.app.customer.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.jboss.jandex</groupId>
          <artifactId>jandex-maven-plugin</artifactId>
          <version>${jandex.maven.plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-maven-plugin</artifactId>
          <version>${quarkus-plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${compiler-plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${surefire-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.openapitools</groupId>
          <artifactId>openapi-generator-maven-plugin</artifactId>
          <version>${openapi.generator.maven.plugin.version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-failsafe-plugin</artifactId>
          <version>${surefire-plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
  <profiles>
    <!-- 
      最新のmvn(3.8.5)を利用した場合、quarkus-maven-pluginではコマンドライン引数(-P xxx)でのプロファイル指定が有効とならない。
      system propertyでのプロファイルの有効化が機能するのでsystem propertyを利用する。
    -->
    <profile>
      <id>default</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <modules>
        <module>nautible-app-ms-customer-core</module>
        <module>nautible-app-ms-customer-aws</module>
        <module>nautible-app-ms-customer-azure</module>
        <module>nautible-app-ms-customer-build</module>
      </modules>
    </profile>
    <profile>
      <id>aws</id>
      <activation>
        <property>
          <name>cloud</name>
          <value>aws</value>
        </property>
      </activation>
      <modules>
        <module>nautible-app-ms-customer-core</module>
        <module>nautible-app-ms-customer-aws</module>
        <module>nautible-app-ms-customer-build</module>
      </modules>
    </profile>
    <profile>
      <id>azure</id>
      <activation>
        <property>
          <name>cloud</name>
          <value>azure</value>
        </property>
      </activation>
      <modules>
        <module>nautible-app-ms-customer-core</module>
        <module>nautible-app-ms-customer-azure</module>
        <module>nautible-app-ms-customer-build</module>
      </modules>
    </profile>
  </profiles>
</project>
